# Generated by Django 5.0.6 on 2024-07-07 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_watchlist_delete_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="auctions.listing",
            ),
        ),
    ]
