# Generated by Django 5.0.6 on 2024-07-08 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_alter_watchlist_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Mobile Phone", "Mobile Phone"),
                            ("Laptops", "Laptops"),
                            ("Cameras", "Cameras"),
                            ("Televisions", "Televisions"),
                            ("Audio Equipment", "Audio Equipment"),
                        ],
                        max_length=64,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="auctions.listing"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to="auctions.category",
            ),
        ),
    ]
