# Generated by Django 5.0.6 on 2024-07-08 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_alter_category_name_alter_listing_image_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="auctions.listing",
            ),
        ),
    ]
